# application.yml
server:
  port: ${PORT:8080}
  servlet:
    context-path: "/pathfinders/v1"

spring:
  application:
    name: pathfinders
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        dialect: ${DATABASE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    thymeleaf:
      cache: true

# swagger-ui and api-docs custom path
springdoc:
  swagger-ui:
    path: "/swagger-ui"
  api-docs:
    path: "/api-docs"